version: "3.8"

services:
  python_code:
    build: ./python_code
    links:
      - s3
    depends_on:
      - s3
    container_name: python_code
    restart: "no"

  s3:
    image: fingershock/fakes3
    ports:
    - "8000:8000"
    container_name: fake_s3